# Generated by Django 4.2.3 on 2023-09-09 16:27

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TestingSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DisplayEachQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_number', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2)),
                ('randomize', models.BooleanField(default=False)),
                ('must_answer', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LimitTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limited_datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SendOffOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('off_or_no', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TakerEmailSendModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.BooleanField(default=False)),
                ('percentage', models.BooleanField(default=False)),
                ('feedback', models.BooleanField(default=False)),
                ('graded', models.BooleanField(default=False)),
                ('Reveal_correct_Answer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TestCompletionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_mark', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('send_completed_message', ckeditor_uploader.fields.RichTextUploadingField()),
                ('send_not_completed_message', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='CreatorEmailSendModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('offno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='off_no', to='AssignLinks.sendoffon')),
            ],
        ),
        migrations.CreateModel(
            name='AssignLinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_field', models.SlugField(max_length=100, unique=True)),
                ('assign_link_foreign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='AssignLinks.availability')),
                ('creator_email_send', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_email', to='AssignLinks.creatoremailsendmodel')),
                ('display_each_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display', to='AssignLinks.displayeachquestion')),
                ('limit_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limit_time', to='AssignLinks.limittime')),
                ('taker_email_send', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taker_email', to='AssignLinks.takeremailsendmodel')),
                ('test_completion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_comp', to='AssignLinks.testcompletionmodel')),
                ('test_foreign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assign_link', to='TestingSystem.test')),
            ],
        ),
    ]
