# Generated by Django 4.2.3 on 2023-09-04 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TestingSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AssignLinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_field', models.SlugField(max_length=100, unique=True)),
                ('assign_link_foreign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='AssignLinks.availability')),
                ('test_foreign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assign_link', to='TestingSystem.test')),
            ],
        ),
    ]
