# Generated by Django 4.2.3 on 2023-09-09 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestingSystem', '0001_initial'),
        ('AssignLinks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignlinkmodel',
            name='assign_link_foreign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='AssignLinks.availability'),
        ),
        migrations.AlterField(
            model_name='assignlinkmodel',
            name='creator_email_send',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_email', to='AssignLinks.creatoremailsendmodel'),
        ),
        migrations.AlterField(
            model_name='assignlinkmodel',
            name='display_each_question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='display', to='AssignLinks.displayeachquestion'),
        ),
        migrations.AlterField(
            model_name='assignlinkmodel',
            name='limit_time',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='limit_time', to='AssignLinks.limittime'),
        ),
        migrations.AlterField(
            model_name='assignlinkmodel',
            name='taker_email_send',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taker_email', to='AssignLinks.takeremailsendmodel'),
        ),
        migrations.AlterField(
            model_name='assignlinkmodel',
            name='test_completion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_comp', to='AssignLinks.testcompletionmodel'),
        ),
        migrations.AlterField(
            model_name='assignlinkmodel',
            name='test_foreign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assign_link', to='TestingSystem.test'),
        ),
        migrations.AlterField(
            model_name='creatoremailsendmodel',
            name='offno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='off_no', to='AssignLinks.sendoffon'),
        ),
    ]
