# Generated by Django 4.2.3 on 2023-09-09 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestingSystem', '0001_initial'),
        ('AssignLinks', '0002_alter_assignlinkmodel_assign_link_foreign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignlinkmodel',
            name='test_foreign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assign_link', to='TestingSystem.test'),
        ),
    ]
