# Generated by Django 4.2.3 on 2023-09-09 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssignLinks', '0003_alter_assignlinkmodel_test_foreign'),
    ]

    operations = [
        migrations.AddField(
            model_name='limittime',
            name='minute',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1440)]),
        ),
    ]
