# Generated by Django 4.2.3 on 2023-08-24 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserResponse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResponseScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_score', to='UserResponse.userinfo')),
            ],
        ),
    ]
