# Generated by Django 4.2.4 on 2023-12-29 11:49

import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('author', models.CharField(max_length=500)),
                ('date_quest', models.DateTimeField(default=datetime.datetime.now)),
                ('slug_link', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Edd',
            fields=[
                ('custom_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('season', models.CharField(max_length=10)),
                ('phone_number', models.BigIntegerField()),
                ('post_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('response_date', models.DateTimeField(default=datetime.datetime.now)),
                ('response_author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('response_title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rel_response_title', to='blogs.cmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='post_image_upload_path')),
                ('slug', models.SlugField(max_length=200)),
                ('publish', models.DateTimeField(default=datetime.datetime.now)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-publish'],
                'indexes': [models.Index(fields=['-publish'], name='blogs_post_publish_693c21_idx')],
            },
        ),
        migrations.CreateModel(
            name='NumQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('description', models.TextField()),
                ('num_quest', models.IntegerField()),
                ('time_quest', models.DateTimeField(default=datetime.datetime.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_auth', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cmodel',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Num_quests', to='blogs.numquest'),
        ),
    ]
