# Generated by Django 4.2.4 on 2023-08-16 20:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='post_images/')),
                ('slug', models.SlugField(max_length=200)),
                ('publish', models.DateTimeField(default=datetime.datetime.now)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-publish'],
                'indexes': [models.Index(fields=['-publish'], name='blogs_post_publish_693c21_idx')],
            },
        ),
    ]
