# Generated by Django 4.2.4 on 2023-08-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edd',
            name='post_id',
            field=models.CharField(max_length=20),
        ),
    ]
