# Generated by Django 4.2.4 on 2024-01-03 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_responsemodel_response_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsemodel',
            name='response_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_response_title', to='blogs.numquest'),
        ),
    ]
