# Generated by Django 4.2.4 on 2024-01-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_responsemodel_response_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numquest',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
