# Generated by Django 4.2.4 on 2023-08-11 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
